job:
  KIND: TrainingJob
  input:
    KIND: ParquetReader
    path: data/nfl_train_data.parquet
  model:
    KIND: RandomForest
  output:
    KIND: ModelWriter
    path: model/random_forest_model.pkl
